### ISSUE TITLE
Rebuild and Deploy Images to fix hs_models issue

### ISSUE THREAD

**Issue by Castronova** [CUAHSI/cuahsi-stacks#26]
Update the Base and Scientific images with the latest hs_models to resolve a pydantic validation issue in hs_on_jh.

**Comment by Castronova** [comment]
@aaraney I just updated the cluster with the latest Python 3 Scientific image. Can you please test to see if this resolves the HydroShare_on_Jupyter issue? 

https://github.com/hydroshare/hydroshare_on_jupyter/issues/100

**Comment by aaraney** [comment]
## Does fix

I verified that this fixes opening HS resources that have an associative `RelationType`. So, for example, https://www.hydroshare.org/resource/ce0f48aff42142b3a12147e8c5113dac/.   For paper trail sake, this was fixed in [`hsmodels` #28](https://github.com/hydroshare/hsmodels/pull/28). 

This resolves the issue in https://github.com/CUAHSI/jupyterhub/issues/1, so I will close that and ref this issue there.

## Does not fix

So, this will not fix opening `CollectionResource`'s as a fix has not been introduced to `hsclient` (see [`hsclient` #25](https://github.com/hydroshare/hsclient/issues/25).
